---

- name: Get vimfiles repo
  git:
    repo: "{{ vimfiles_repo }}"
    dest: "{{ vimfiles_dir }}"
  tags:
    - vimfiles

- name: symlink vimrc file
  file: 
    src: "{{ vimfiles_dir }}/.vim/vimrc"
    dest: ~/.vimrc
    state: link

# - name: Install YCM
#   command: "{{ ycm_install_cmd }}"
#   args:
#     chdir: "{{ vimfiles_dir }}"
#     creates: "{{ ycm_installed_file }}"
#   tags:
#     - vimfiles

- name: Install MacVim
  homebrew:
    name: macvim
    install_options: "{{ macvim_install_options }}"
    state: latest
  tags:
    - vimfiles
    - brew
